Rename and remove error type
infinum/flutter-bits pull request #26
Opened 2022-10-11 08:55 UTC by itsJoKr

2022-10-11 11:22 UTC, Truba approved these changes

2022-10-11 12:56 UTC, zenled requested changes

2022-10-11 12:56 UTC, zenled commented on request_provider/README.md
>  class MyRequestProvider extends RequestProvider<Data> {
Change `RequestProvider` -> `RequestNotifier`.

2022-10-11 12:56 UTC, zenled commented on request_provider/__brick__/request_state.dart
> +  Object? get error => maybeWhen(orElse: () => null, failure: (error) => error);
Change the extension name to something more general, something like `RequestStateExtension`.
Add `isInitial`, `isSuccess` and `isFailure`, just like we have `isLoading`.

2022-10-11 12:56 UTC, zenled commented on request_provider/__brick__/request_notifier.dart
> +    Exception? Function(Object)? errorHandler,
The signature of `errorHandler` is a bit confusing (take a look at the underlying implementation of `executeRequest`).

1. The object passed to `errorHandler` will always be an `Exception`.
2. Why does `errorHandler` need to return an `Exception`, if the `RequestState.failure` can receive any object?

2022-10-21 11:07 UTC, itsJoKr commented on request_provider/README.md
I fixed other issues. I will merge now and check this issue latter. This might break our brick so I need to see sync with Dario.

2022-10-21 11:08 UTC, merged

2022-11-10 14:14 UTC, Fle9ma commented on request_provider/README.md
@itsJoKr
Any changes to this repo will not cause the brick to stop working. Brick is working perfectly with the latest changes 🙌🏻
I also tested `infinum_architecture` brick, and all is good 💪🏻